print("Giraffe Academy")
print("Giraffe\"Academy")
print("Giraffe\nAcademy")

phrase = "Giraffe Academy"
print(phrase + " is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase.index("G"))
print(phrase.index("a"))
print(phrase.index("Acad"))
print(phrase.replace("Giraffe","Elephant"))